
package views;
import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import models.Aeropuerto;
import models.Avion;
import models.Piloto;
import models.Usuario;
import models.Vuelo;
import services.AeropuertoService;
import services.AvionService;
import services.PilotoService;
import services.VueloService;

public class AdminForm extends javax.swing.JFrame {

    private static final PilotoService pilotoService = new PilotoService();
    private static final AeropuertoService aeropuertoService = new AeropuertoService();
    private static final AvionService avionService = new AvionService();
    private static final VueloService vueloService = new VueloService();
    private static Usuario usuario;
    
    public AdminForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public AdminForm(Usuario usuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.usuario = usuario;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        LoginForm1 = new util.RoundPanel(25, new Color(239,239,239));
        LoginTItle1 = new javax.swing.JLabel();
        txtApellidoPilot = new util.RoundJTextField();
        btnRegistrarPiloto = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNombrePilot = new util.RoundJTextField();
        cboExperienciaPilot = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        LoginForm3 = new util.RoundPanel(25, new Color(239,239,239));
        LoginTItle3 = new javax.swing.JLabel();
        txtAeropuertoNombre = new util.RoundJTextField();
        btnRegistrarAeropuertos = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtPaisAeropuerto = new util.RoundJTextField();
        txtProvinciaNombre = new util.RoundJTextField();
        txtCiudadAero = new util.RoundJTextField();
        jPanel3 = new javax.swing.JPanel();
        LoginForm2 = new util.RoundPanel(25, new Color(239,239,239));
        LoginTItle2 = new javax.swing.JLabel();
        txtModelo = new util.RoundJTextField();
        btnRegistrarAvion = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtFabricante = new util.RoundJTextField();
        txtNumAsientos = new util.RoundJTextField();
        cboAeropuertosAv = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        LoginForm = new util.RoundPanel(25, new Color(239,239,239));
        LoginTItle = new javax.swing.JLabel();
        txtCiudadDestino = new util.RoundJTextField();
        btnRegistrarVuelo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtOrigen = new util.RoundJTextField();
        cboAeropuertosVue = new javax.swing.JComboBox<>();
        cboPilotosVue = new javax.swing.JComboBox<>();
        cboAviones = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(720, 520));
        setMinimumSize(new java.awt.Dimension(720, 520));
        setResizable(false);

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        LoginForm1.setBackground(new java.awt.Color(204, 204, 255));
        LoginForm1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginTItle1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LoginTItle1.setForeground(new java.awt.Color(102, 102, 255));
        LoginTItle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginTItle1.setText("Nuevo Piloto");
        LoginForm1.add(LoginTItle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 490, -1));
        LoginForm1.add(txtApellidoPilot, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 230, 36));

        btnRegistrarPiloto.setBackground(new java.awt.Color(51, 153, 255));
        btnRegistrarPiloto.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btnRegistrarPiloto.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarPiloto.setText("Registrar");
        btnRegistrarPiloto.setBorder(null);
        btnRegistrarPiloto.setBorderPainted(false);
        btnRegistrarPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPilotoActionPerformed(evt);
            }
        });
        LoginForm1.add(btnRegistrarPiloto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 230, 43));

        jLabel9.setText("Nombre");
        LoginForm1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 230, -1));

        jLabel10.setText("Experiencia");
        LoginForm1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 230, -1));

        jLabel14.setText("Apellido");
        LoginForm1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 230, -1));
        LoginForm1.add(txtNombrePilot, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 230, 36));

        cboExperienciaPilot.setBackground(new java.awt.Color(255, 255, 255));
        cboExperienciaPilot.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baja", "Media", "Alta" }));
        cboExperienciaPilot.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        LoginForm1.add(cboExperienciaPilot, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 230, 40));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(LoginForm1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(LoginForm1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registrar Pilotos", jPanel2);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        LoginForm3.setBackground(new java.awt.Color(204, 204, 255));
        LoginForm3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginTItle3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LoginTItle3.setForeground(new java.awt.Color(102, 102, 255));
        LoginTItle3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginTItle3.setText("Nuevo Aeropuerto");
        LoginForm3.add(LoginTItle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 490, -1));
        LoginForm3.add(txtAeropuertoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 230, 36));

        btnRegistrarAeropuertos.setBackground(new java.awt.Color(51, 153, 255));
        btnRegistrarAeropuertos.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btnRegistrarAeropuertos.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarAeropuertos.setText("Registrar");
        btnRegistrarAeropuertos.setBorder(null);
        btnRegistrarAeropuertos.setBorderPainted(false);
        btnRegistrarAeropuertos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAeropuertosActionPerformed(evt);
            }
        });
        LoginForm3.add(btnRegistrarAeropuertos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 490, 43));

        jLabel25.setText("Pais");
        LoginForm3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 230, -1));

        jLabel26.setText("Provincia");
        LoginForm3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 230, -1));

        jLabel28.setText("Ciudad");
        LoginForm3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 230, -1));

        jLabel30.setText("Nombre");
        LoginForm3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 230, -1));
        LoginForm3.add(txtPaisAeropuerto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 230, 36));
        LoginForm3.add(txtProvinciaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 230, 36));
        LoginForm3.add(txtCiudadAero, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 230, 36));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(LoginForm3, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(LoginForm3, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registrar Aeropuertos", jPanel4);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        LoginForm2.setBackground(new java.awt.Color(204, 204, 255));
        LoginForm2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginTItle2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LoginTItle2.setForeground(new java.awt.Color(102, 102, 255));
        LoginTItle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginTItle2.setText("Nuevo Avion");
        LoginForm2.add(LoginTItle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 490, -1));
        LoginForm2.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 230, 36));

        btnRegistrarAvion.setBackground(new java.awt.Color(51, 153, 255));
        btnRegistrarAvion.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btnRegistrarAvion.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarAvion.setText("Registrar");
        btnRegistrarAvion.setBorder(null);
        btnRegistrarAvion.setBorderPainted(false);
        btnRegistrarAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAvionActionPerformed(evt);
            }
        });
        LoginForm2.add(btnRegistrarAvion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 490, 43));

        jLabel17.setText("Fabricante");
        LoginForm2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 230, -1));

        jLabel18.setText("Número Asientos");
        LoginForm2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 230, -1));

        jLabel20.setText("Aeropuerto");
        LoginForm2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 230, -1));

        jLabel22.setText("Modelo");
        LoginForm2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 230, -1));

        txtFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFabricanteActionPerformed(evt);
            }
        });
        LoginForm2.add(txtFabricante, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 230, 36));
        LoginForm2.add(txtNumAsientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 230, 36));

        cboAeropuertosAv.setBackground(new java.awt.Color(255, 255, 255));
        cboAeropuertosAv.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        LoginForm2.add(cboAeropuertosAv, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 230, 40));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(LoginForm2, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(LoginForm2, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registrar Aviones", jPanel3);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        LoginForm.setBackground(new java.awt.Color(204, 204, 255));
        LoginForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginTItle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LoginTItle.setForeground(new java.awt.Color(102, 102, 255));
        LoginTItle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginTItle.setText("Nuevo Vuelo");
        LoginForm.add(LoginTItle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 490, -1));
        LoginForm.add(txtCiudadDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 230, 36));

        btnRegistrarVuelo.setBackground(new java.awt.Color(51, 153, 255));
        btnRegistrarVuelo.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btnRegistrarVuelo.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarVuelo.setText("Registrar");
        btnRegistrarVuelo.setBorder(null);
        btnRegistrarVuelo.setBorderPainted(false);
        btnRegistrarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVueloActionPerformed(evt);
            }
        });
        LoginForm.add(btnRegistrarVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 490, 43));

        jLabel1.setText("Ciudad Origen");
        LoginForm.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 230, -1));

        jLabel2.setText("Aeropuerto");
        LoginForm.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 230, -1));

        jLabel4.setText("Piloto");
        LoginForm.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 230, -1));

        jLabel6.setText("Ciudad Destino");
        LoginForm.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 230, -1));

        txtOrigen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtOrigenFocusLost(evt);
            }
        });
        LoginForm.add(txtOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 230, 36));

        cboAeropuertosVue.setBackground(new java.awt.Color(255, 255, 255));
        cboAeropuertosVue.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        LoginForm.add(cboAeropuertosVue, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 230, 40));

        cboPilotosVue.setBackground(new java.awt.Color(255, 255, 255));
        cboPilotosVue.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        LoginForm.add(cboPilotosVue, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 230, 40));

        cboAviones.setBackground(new java.awt.Color(255, 255, 255));
        cboAviones.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        LoginForm.add(cboAviones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 490, 40));

        jLabel3.setText("Avion");
        LoginForm.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 230, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(LoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(LoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registrar Vuelos", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVueloActionPerformed
        String ciudadOrigen = txtOrigen.getText();
        String ciudadDestino = txtCiudadDestino.getText();
        Aeropuerto aeropuerto = aeropuertoService.recuperarAeropuetoByNombre(cboAeropuertosVue.getSelectedItem().toString());
        Piloto piloto = pilotoService.recuperarPilotoById(cboPilotosVue.getSelectedIndex()+1);
        System.out.println(cboAviones.getSelectedIndex());
        Avion avion = avionService.recuperarAvionById(cboAviones.getSelectedIndex()+1);
        
        
        Vuelo vuelo = new Vuelo(ciudadOrigen,ciudadDestino, aeropuerto, avion, piloto);
        
        vueloService.guardar(vuelo);
    }//GEN-LAST:event_btnRegistrarVueloActionPerformed

    private void btnRegistrarPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPilotoActionPerformed
        try{
            String nombrePilot = txtNombrePilot.getText();
            String apellidoPilot = txtApellidoPilot.getText();
            int experienciaPilot = cboExperienciaPilot.getSelectedIndex()+1;
            Piloto piloto = new Piloto(nombrePilot, apellidoPilot, experienciaPilot);
            pilotoService.guardar(piloto);
            JOptionPane.showMessageDialog(null, "Piloto agregado correctamente");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error: "+ex.getMessage());
        }
        
    }//GEN-LAST:event_btnRegistrarPilotoActionPerformed

    private void btnRegistrarAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAvionActionPerformed
        String fabricante = txtFabricante.getText();
        String modelo = txtModelo.getText();
        int numAsientos = Integer.parseInt(txtNumAsientos.getText());
        Aeropuerto aeropuerto = aeropuertoService.recuperarAeropuetoByNombre(cboAeropuertosAv.getSelectedItem().toString());
        Avion avion = new Avion(modelo, numAsientos, fabricante, aeropuerto);
        avion.toString();
        avionService.guardar(avion);
    }//GEN-LAST:event_btnRegistrarAvionActionPerformed

    private void btnRegistrarAeropuertosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAeropuertosActionPerformed
        String pais = txtPaisAeropuerto.getText();
        String nombre = txtAeropuertoNombre.getText();
        String provincia = txtProvinciaNombre.getText();
        String ciudad = txtCiudadAero.getText();
        Aeropuerto aeropuerto = new Aeropuerto(nombre,ciudad,provincia,pais);
        aeropuertoService.guardar(aeropuerto);
    }//GEN-LAST:event_btnRegistrarAeropuertosActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        DefaultComboBoxModel aeroModels = new DefaultComboBoxModel();
        for(Aeropuerto aeropuerto : aeropuertoService.listar()){
            aeroModels.addElement(aeropuerto.getNombreAeropuerto());
        }
        
        cboAeropuertosAv.setModel(aeroModels);
        
        DefaultComboBoxModel pilotoModels = new DefaultComboBoxModel();
        for(Piloto piloto : pilotoService.listar()){
            pilotoModels.addElement(piloto.getNombre()+" "+piloto.getApellido());
        }
        
        cboPilotosVue.setModel(pilotoModels);
        
        DefaultComboBoxModel avionModels = new DefaultComboBoxModel();
        for(Avion avion : avionService.listar()){
            avionModels.addElement(avion.getModelo());
        }
        
        cboAviones.setModel(avionModels);
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void txtFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFabricanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFabricanteActionPerformed

    private void txtOrigenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOrigenFocusLost
        DefaultComboBoxModel aerosCityModels = new DefaultComboBoxModel();
        String ciuOrigen = txtOrigen.getText();
        for(Aeropuerto aeropuerto : aeropuertoService.recuperarAeropuertosByCiudad(ciuOrigen)){
            aerosCityModels.addElement(aeropuerto.getNombreAeropuerto());
        }
        cboAeropuertosVue.setModel(aerosCityModels);
    }//GEN-LAST:event_txtOrigenFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginForm;
    private javax.swing.JPanel LoginForm1;
    private javax.swing.JPanel LoginForm2;
    private javax.swing.JPanel LoginForm3;
    private javax.swing.JLabel LoginTItle;
    private javax.swing.JLabel LoginTItle1;
    private javax.swing.JLabel LoginTItle2;
    private javax.swing.JLabel LoginTItle3;
    private javax.swing.JButton btnRegistrarAeropuertos;
    private javax.swing.JButton btnRegistrarAvion;
    private javax.swing.JButton btnRegistrarPiloto;
    private javax.swing.JButton btnRegistrarVuelo;
    private javax.swing.JComboBox<String> cboAeropuertosAv;
    private javax.swing.JComboBox<String> cboAeropuertosVue;
    private javax.swing.JComboBox<String> cboAviones;
    private javax.swing.JComboBox<String> cboExperienciaPilot;
    private javax.swing.JComboBox<String> cboPilotosVue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private util.RoundJTextField txtAeropuertoNombre;
    private util.RoundJTextField txtApellidoPilot;
    private util.RoundJTextField txtCiudadAero;
    private util.RoundJTextField txtCiudadDestino;
    private util.RoundJTextField txtFabricante;
    private util.RoundJTextField txtModelo;
    private util.RoundJTextField txtNombrePilot;
    private util.RoundJTextField txtNumAsientos;
    private util.RoundJTextField txtOrigen;
    private util.RoundJTextField txtPaisAeropuerto;
    private util.RoundJTextField txtProvinciaNombre;
    // End of variables declaration//GEN-END:variables
}
