
package views;

import java.awt.Color;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.Pasajero;
import models.Usuario;
import services.PasajeroService;
import services.UsuarioService;
import util.Hash;

public class RegisterForm extends javax.swing.JFrame {

    public static final PasajeroService pasajeroService = new PasajeroService();
    public static final UsuarioService usuarioService = new UsuarioService();
    
    public RegisterForm() {
        initComponents();
        this.setLocationRelativeTo(null);;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LoginForm = new util.RoundPanel(25, new Color(239,239,239));
        LoginTItle = new javax.swing.JLabel();
        txtFechaNac = new util.RoundJTextField();
        btnRegistrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNombre = new util.RoundJTextField();
        txtApellido = new util.RoundJTextField();
        txtTelefono = new util.RoundJTextField();
        txtDireccion = new util.RoundJTextField();
        txtEmail = new util.RoundJTextField();
        txtUsuario = new util.RoundJTextField();
        txtPassword = new util.RoundJPassField();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro");
        setBackground(new java.awt.Color(204, 204, 255));
        setMaximumSize(new java.awt.Dimension(720, 520));
        setMinimumSize(new java.awt.Dimension(720, 520));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        LoginForm.setBackground(new java.awt.Color(204, 204, 255));
        LoginForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginTItle.setForeground(new java.awt.Color(102, 102, 255));
        LoginTItle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginTItle.setText("Nuevo Usuario");
        LoginForm.add(LoginTItle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 490, -1));
        LoginForm.add(txtFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 230, 36));

        btnRegistrar.setBackground(new java.awt.Color(51, 153, 255));
        btnRegistrar.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(null);
        btnRegistrar.setBorderPainted(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        LoginForm.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 490, 43));

        jLabel1.setText("Nombre");
        LoginForm.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 230, -1));

        jLabel2.setText("Apellido");
        LoginForm.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 230, -1));

        jLabel3.setText("Direccion");
        LoginForm.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 230, -1));

        jLabel4.setText("Telefono");
        LoginForm.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 230, -1));

        jLabel5.setText("Email");
        LoginForm.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 230, -1));

        jLabel6.setText("Fecha Nacimiento");
        LoginForm.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 230, -1));

        jLabel7.setText("Usuario");
        LoginForm.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 230, -1));

        jLabel8.setText("Password");
        LoginForm.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 226, -1));
        LoginForm.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 230, 36));
        LoginForm.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 230, 36));
        LoginForm.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 230, 36));
        LoginForm.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 230, 36));
        LoginForm.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 230, 36));
        LoginForm.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 230, 36));
        LoginForm.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 230, -1));

        btnRegresar.setBackground(new java.awt.Color(51, 153, 255));
        btnRegresar.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("<");
        btnRegresar.setBorder(null);
        btnRegresar.setBorderPainted(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(LoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try{
            if(!txtNombre.getText().equals("") && !txtTelefono.getText().equals("") && !txtTelefono.getText().equals("") && !txtDireccion.getText().equals("") && !txtEmail.getText().equals("")  && !txtUsuario.getText().equals("") && !txtPassword.getPassword().equals("")){
                String nombre = txtNombre.getText();
                String apellido = txtApellido.getText();
                String telefono = txtTelefono.getText();
                String direccion = txtDireccion.getText();
                String email = txtEmail.getText();
                String nombreUsuario = txtUsuario.getText();
                String pass = Hash.sha1(new String(txtPassword.getPassword()));
                Date fechaNac = null;
                try {
                    fechaNac = new SimpleDateFormat("yyyy-MM-dd").parse(txtFechaNac.getText());
                } catch (ParseException ex) {
                    Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
                }

                Usuario usuario = new Usuario(nombreUsuario, pass, "user");
                Pasajero pasajero = new Pasajero(nombre, apellido, direccion, telefono, email, fechaNac);
                usuario.setPasajero(pasajero);
                pasajero.setUsuario(usuario);

                pasajeroService.guardar(pasajero);
                JOptionPane.showMessageDialog(null, "Usuario Registrado Correctamente");
            }else{
                JOptionPane.showMessageDialog(null, "Es necesario rellenar todos los datos");
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error: "+ex.getMessage());
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
        LoginForm lf = new LoginForm();
        lf.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginForm;
    private javax.swing.JLabel LoginTItle;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private util.RoundJTextField txtApellido;
    private util.RoundJTextField txtDireccion;
    private util.RoundJTextField txtEmail;
    private util.RoundJTextField txtFechaNac;
    private util.RoundJTextField txtNombre;
    private util.RoundJPassField txtPassword;
    private util.RoundJTextField txtTelefono;
    private util.RoundJTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
