
package views;

import java.awt.Color;

public class ReservaForm extends javax.swing.JFrame {

    /**
     * Creates new form ReservaForm
     */
    public ReservaForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Content = new javax.swing.JPanel();
        LoginForm = new util.RoundPanel(25,new Color(239,239,239));
        LoginTItle = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        lblComprarBoletos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(720, 520));
        setMinimumSize(new java.awt.Dimension(720, 520));
        setResizable(false);

        Content.setBackground(new java.awt.Color(204, 204, 255));

        LoginForm.setBackground(new java.awt.Color(204, 204, 255));
        LoginForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginTItle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LoginTItle.setForeground(new java.awt.Color(102, 102, 255));
        LoginTItle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginTItle.setText("Reserva de Vuelos");
        LoginForm.add(LoginTItle, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 31, 540, -1));

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Buscar Vuelos");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        LoginForm.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 140, 40));

        LoginForm.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 180, 40));

        LoginForm.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 180, 40));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("Destino");
        LoginForm.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 180, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("Origen");
        LoginForm.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 180, -1));

        jScrollPane1.setViewportView(jList1);

        LoginForm.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 540, -1));

        lblComprarBoletos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblComprarBoletos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComprarBoletos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add-icon.png"))); // NOI18N
        lblComprarBoletos.setText("Comprar Boletos");
        lblComprarBoletos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblComprarBoletosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblComprarBoletosMouseExited(evt);
            }
        });
        LoginForm.add(lblComprarBoletos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 540, -1));

        javax.swing.GroupLayout ContentLayout = new javax.swing.GroupLayout(Content);
        Content.setLayout(ContentLayout);
        ContentLayout.setHorizontalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(LoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        ContentLayout.setVerticalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(LoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lblComprarBoletosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblComprarBoletosMouseEntered
        lblComprarBoletos.setForeground(new Color(51,153,255));
    }//GEN-LAST:event_lblComprarBoletosMouseEntered

    private void lblComprarBoletosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblComprarBoletosMouseExited
        lblComprarBoletos.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblComprarBoletosMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JPanel LoginForm;
    private javax.swing.JLabel LoginTItle;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblComprarBoletos;
    // End of variables declaration//GEN-END:variables
}
