
package views;

import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import models.Usuario;
import models.Vuelo;
import services.AeropuertoService;
import services.AvionService;
import services.PilotoService;
import services.VueloService;

public class ReservaForm extends javax.swing.JFrame {

    
    private static final PilotoService pilotoService = new PilotoService();
    private static final AeropuertoService aeropuertoService = new AeropuertoService();
    private static final AvionService avionService = new AvionService();
    private static final VueloService vueloService = new VueloService();
    private static Usuario usuario;
    
    public ReservaForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }
    
    
    public ReservaForm(Usuario usuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.usuario = usuario;
        lblUsuario.setText(this.usuario.getNombreUsuario());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Content = new javax.swing.JPanel();
        LoginForm = new util.RoundPanel(25,new Color(239,239,239));
        LoginTItle = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cboDestino = new javax.swing.JComboBox<>();
        cboOrigen = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listVuelos = new javax.swing.JList<>();
        lblComprarBoletos = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        LoginTItle1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(720, 520));
        setMinimumSize(new java.awt.Dimension(720, 520));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Content.setBackground(new java.awt.Color(204, 204, 255));

        LoginForm.setBackground(new java.awt.Color(204, 204, 255));
        LoginForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginTItle.setForeground(new java.awt.Color(102, 102, 255));
        LoginTItle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginTItle.setText("Usuario:");
        LoginForm.add(LoginTItle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 70, 40));

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Buscar Vuelos");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        LoginForm.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 140, 40));

        cboDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDestinoActionPerformed(evt);
            }
        });
        LoginForm.add(cboDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 180, 40));

        cboOrigen.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboOrigenItemStateChanged(evt);
            }
        });
        LoginForm.add(cboOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 180, 40));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("Destino");
        LoginForm.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 180, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("Origen");
        LoginForm.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 180, -1));

        jScrollPane1.setViewportView(listVuelos);

        LoginForm.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 540, -1));

        lblComprarBoletos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblComprarBoletos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComprarBoletos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add-icon.png"))); // NOI18N
        lblComprarBoletos.setText("Comprar Boletos");
        lblComprarBoletos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblComprarBoletosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblComprarBoletosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblComprarBoletosMouseExited(evt);
            }
        });
        LoginForm.add(lblComprarBoletos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 540, -1));

        jLabel3.setText("Avion");
        LoginForm.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        jLabel4.setText("Id");
        LoginForm.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel5.setText("Origen");
        LoginForm.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        jLabel6.setText("Destino");
        LoginForm.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        lblUsuario.setText("nombreUsuario");
        LoginForm.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 140, 40));

        LoginTItle1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LoginTItle1.setForeground(new java.awt.Color(102, 102, 255));
        LoginTItle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginTItle1.setText("Reserva de Vuelos");
        LoginForm.add(LoginTItle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 31, 540, -1));

        javax.swing.GroupLayout ContentLayout = new javax.swing.GroupLayout(Content);
        Content.setLayout(ContentLayout);
        ContentLayout.setHorizontalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(LoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        ContentLayout.setVerticalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(LoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultListModel vuelos = new DefaultListModel();
        String origen = cboOrigen.getSelectedItem().toString();
        String destino = cboDestino.getSelectedItem().toString();
        for(Vuelo vuelo : vueloService.recuperarDestinosByOrigenAndDestino(origen, destino)){
            vuelos.addElement(" "+vuelo.getId()+"          "+vuelo.getCiudadOrigen()+"          "+vuelo.getCiudadDestino()+"          "+vuelo.getAvion().getFabricante()+" "+vuelo.getAvion().getModelo());
        }
        
        listVuelos.setModel(vuelos);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lblComprarBoletosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblComprarBoletosMouseEntered
        lblComprarBoletos.setForeground(new Color(51,153,255));
    }//GEN-LAST:event_lblComprarBoletosMouseEntered

    private void lblComprarBoletosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblComprarBoletosMouseExited
        lblComprarBoletos.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblComprarBoletosMouseExited

    private void cboOrigenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboOrigenItemStateChanged
        DefaultComboBoxModel destinoModels = new DefaultComboBoxModel();
        
        String origen = cboOrigen.getSelectedItem().toString();
        
        for(Vuelo vuelo : vueloService.listar()){
            destinoModels.addElement(vuelo.getCiudadDestino());
        }
        
        cboDestino.setModel(destinoModels);
        
    }//GEN-LAST:event_cboOrigenItemStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DefaultComboBoxModel origenModels = new DefaultComboBoxModel();
        
        origenModels.addElement("Seleccione un Origen");
        for(Vuelo vuelo : vueloService.listar()){
            origenModels.addElement(vuelo.getCiudadOrigen());
        }
        
        cboOrigen.setModel(origenModels);
    }//GEN-LAST:event_formWindowOpened

    private void lblComprarBoletosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblComprarBoletosMouseClicked
        if(!listVuelos.isSelectionEmpty()){
            Usuario usuario = this.usuario;
            Vuelo vuelo = vueloService.recuperarVueloById(listVuelos.getSelectedIndex()+1);
            TicketForm tf = new TicketForm(vuelo, usuario);
            tf.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar un vuelo de la lista antes de comprar");
        }
        
    }//GEN-LAST:event_lblComprarBoletosMouseClicked

    private void cboDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDestinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JPanel LoginForm;
    private javax.swing.JLabel LoginTItle;
    private javax.swing.JLabel LoginTItle1;
    private javax.swing.JComboBox<String> cboDestino;
    private javax.swing.JComboBox<String> cboOrigen;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblComprarBoletos;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JList<String> listVuelos;
    // End of variables declaration//GEN-END:variables
}
